### ISSUE TITLE
Server Side Hitting using React Component

### ISSUE THREAD

**Issue by reshma-96** [ag-grid/ag-grid-server-side-nodejs-example#1]
I'm using React Components of ag-grid. But we are having Restful Api's to connect with api's. Can i get the proper doc for React Component which hits each time on Server when i'm using Sorting, Filtering etc. In the given docs, the api consists of whole data in one api and node.js server will manipulate using sql querying.
In this git doc, you are not using React. So pls share React component example.

**Comment by rmc-software** [comment]
The SSRM docs have been updated to use an in-memory db that works in browsers called [AlaSql](http://alasql.org/). Each of our examples contains a React version. For instance in the [Server-side Sorting](https://www.ag-grid.com/javascript-grid-server-side-model-sorting/#example-server-side-sorting) section you will see this [React Example](https://plnkr.co/edit/scyJNyF5r624mtVn).
